repos:
  ###### FORMATTING ######
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (pyi)
        types: [pyi]

  ###### LINTING ######
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.2
    hooks:
      - id: bandit
        args: ["--baseline", "tests/known_issues.json"]

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
      # any flake8 plugins must be included in the hook venv
      # additional_dependencies: [flake8-docstrings]

  # - repo: https://github.com/PyCQA/pylint
  #   rev: v2.8.2
  #   hooks:
  #     - id: pylint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: mixed-line-ending
        args: [--fix=no]

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==21.5b1]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-no-eval
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
